add common implementation of geojson data source, with feature using …
cuhacking/atlas pull request #40
Opened 2020-09-03 02:45 UTC by ghaskins99

resolves #19.

2020-09-03 14:40 UTC, WillMahler reviewed
Looks good to me!

2020-09-03 15:23 UTC, dellisd approved these changes

2020-09-03 16:56 UTC, dellisd requested changes
These should actually be covered by the `api` call in the `commonMain` dependencies, no?

2020-09-03 16:56 UTC, dellisd commented on common/build.gradle.kts
> +        implementation(deps.spatialk.geojson)
```suggestion
```

2020-09-03 16:56 UTC, dellisd commented on common/build.gradle.kts
> +        api(deps.spatialk.geojson)
```suggestion
```

2020-09-03 17:23 UTC, WillMahler approved these changes

2020-09-03 20:41 UTC, dellisd approved these changes

2020-09-03 21:22 UTC, dellisd requested changes
Change the android implemnetation to use your new data source class

2020-09-03 23:30 UTC, dellisd requested changes
One last thing:
Can we move all mapbox-related code to the `mapbox` module (instead of `common`) and put it all in the `com.cuhacking.mapbox` package?

2020-09-04 20:04 UTC, dellisd approved these changes

2020-09-05 03:05 UTC, merged