Add logic for downloading map data into database
cuhacking/atlas pull request #52
Opened 2020-10-12 04:46 UTC by safa-howaid

`server.url=<random url>` should be added in the `local.properties` file for the build to run successfully.

2020-10-12 05:57 UTC, dellisd requested changes

2020-10-12 05:57 UTC, dellisd commented on .github/workflows/gradle-check.yml
> +      run: echo server.url=https://example.com/ > local.properties
```suggestion
      env:
        MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
      run: |
        echo mapbox.key="$MAPBOX_KEY" > local.properties
        echo server.url=https://example.com/ > local.properties
```
Fancy multi-line yml syntax

2020-10-12 05:57 UTC, dellisd commented on common/src/androidTest/kotlin/FeatureApiTest.kt
> +}
```suggestion
    fun `check that data is downloaded and inserted to database`() = runBlocking {
        FeatureApi(database, client).getAndStoreFeatures()
       
        assertEquals(database.featureQueries.getAll().executeAsList(),featureList)
    }
}
```

Minor style change

2020-10-12 05:57 UTC, dellisd commented on common/src/commonMain/kotlin/com/cuhacking/atlas/common/FeatureApi.kt
> +    private fun Feature.toDataFeature() = com.cuhacking.atlas.db.Feature(
```suggestion
    private fun Feature.toDataFeature() = DbFeature(
```
You can import this as an alias.
```kotlin
import com.cuhacking.atlas.db.Feature as DbFeature
```

2020-10-12 05:57 UTC, dellisd commented on common/src/commonMain/kotlin/com/cuhacking/atlas/common/FeatureApi.kt
> +    suspend fun getAndStoreFeatures() {
```suggestion
    suspend fun getAndStoreFeatures() = withContext(dispatchers.io) {
```
We want our network requests to run on the I/O thread

2020-10-12 15:14 UTC, dellisd approved these changes

2020-10-13 00:45 UTC, ghaskins99 approved these changes

2020-10-13 00:47 UTC, merged