iOS Search Bar
cuhacking/atlas pull request #78
Opened 2021-05-16 20:23 UTC by WillMahler

- Added iOS search bar, still needs to be connected
   to database

2021-05-16 20:26 UTC, WillMahler commented
This video was the most helpful one I had found when it came to implementing this:
https://www.youtube.com/watch?v=vgvbrBX2FnE

2021-07-26 01:36 UTC, dellisd requested changes

2021-07-26 01:36 UTC, dellisd commented on ios/atlas/SearchViewModelWrapper.swift
> +            onError: {throwable in
```suggestion
            onError: { throwable in
```

2021-07-26 01:48 UTC, safa-howaid commented on ios/atlas/SearchView.swift
> +            viewModel.getSearchResults(query: query)
yup

2021-07-26 01:50 UTC, dellisd commented on ios/atlas/SearchView.swift
> +            viewModel.getSearchResults(query: query)
Would it make more sense to define it above `query`? 🤔

2021-07-26 01:51 UTC, safa-howaid commented on ios/atlas/SearchView.swift
> +            viewModel.getSearchResults(query: query)
probably haha

2021-07-26 03:23 UTC, dellisd approved these changes

2021-07-26 03:23 UTC, merged